name: Auto PR from dev to main
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge dev into main
          branch: dev
          base: main
          title: 'Update Resource Pack'
          body: 'This PR was automatically created by a GitHub Action.'
