name: Auto PR from dev to main

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Create PR from dev to main
          branch: dev
          base: main
          title: 'Auto PR: Merge dev into main'
          body: 'This PR was automatically created by a GitHub Action.'
